version: "3.6"

#################################################
####### launch instruction:
####### START:    docker compose --profile mytag up
####### STOP:     docker compose --profile mytag down
####### HASURA:   http://localhost:8091
####### PGADMIN:  http://localhost:6091
#################################################


services:

  postgres:
    image: postgres:14
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql-engine:
    image: hasura/graphql-engine:v2.33.4
    ports:
      - "8091:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      HASURA_GRAPHQL_CORS_DOMAIN: https://jupyterlite.readthedocs.io, http://localhost:3000
      HASURA_GRAPHQL_ADMIN_SECRET: osolemio


  pgadmin:
    image: dpage/pgadmin4:2023-08-21-1
    restart: always
    ports:
      - "6091:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: "0"
      PGADMIN_CONFIG_LOGIN_BANNER: '"PH-Local: Work without fear !"'
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: '10'
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data:

